name: CI
on:
  push:
    branches: ["main"]

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU (Linux/arm64 Only)
        if: runner.os == 'Linux'
        uses: docker/setup-qemu-action@v3
        with:
          platforms: all
      - name: Set up emulated deps
        run: |
          sudo dpkg --add-architecture arm64
          cat > /etc/apt/sources.list.d/arm64.list <<EOF
          deb [arch=arm64] http://archive.ubuntu.com/ubuntu/ jammy main restricted universe multiverse
          deb [arch=arm64] http://archive.ubuntu.com/ubuntu/ jammy-updates main restricted universe multiverse
          deb [arch=arm64] http://archive.ubuntu.com/ubuntu/ jammy-security main restricted universe multiverse
          deb [arch=arm64] http://archive.ubuntu.com/ubuntu/ jammy-backports main restricted universe multiverse
          EOF
          sudo apt update
          sudo apt install libc6:arm64
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.12
          architecture: arm64
      - name: Test
        run: python -c 'import platform; print(platform.architecture())'
