name: CI
on:
  push:
    branches: ["main"]

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU (Linux/arm64 Only)
        if: runner.os == 'Linux'
        uses: docker/setup-qemu-action@v3
        with:
          platforms: all
      - name: Set up emulated deps
        run: |
          sudo dpkg --add-architecture arm64 aarch64
          sudo apt-get install libc6:arm64
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.12
          architecture: arm64
      - name: Test
        run: python -c 'import platform; print(platform.architecture())'
